AWSTemplateFormatVersion: '2010-09-09'
Description: StrictOps cross-account IAM role for onboarding.

Parameters:
  RoleName:
    Type: String
    Default: StrictOpsAccess
    Description: Name of the IAM role StrictOps will assume.
  ExternalId:
    Type: String
    Description: External ID provided by StrictOps during onboarding.
  StrictOpsAccountId:
    Type: String
    Description: AWS account ID for StrictOps that can assume the role.

Resources:
  StrictOpsCrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${StrictOpsAccountId}:root
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      Policies:
        - PolicyName: StrictOpsRequiredPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:DescribeClusters
                  - ecs:DescribeServices
                  - ecs:DescribeTaskDefinition
                  - ecs:ListServices
                  - ecs:ListTaskDefinitions
                  - ecs:RegisterTaskDefinition
                  - ecs:DeregisterTaskDefinition
                  - ecs:UpdateService
                  - ecs:CreateService
                  - ecs:DeleteService
                  - ecs:CreateCluster
                  - ecs:DeleteCluster
                  - ecs:TagResource
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:CreateRepository
                  - ecr:DeleteRepository
                  - ecr:DescribeRepositories
                  - ecr:GetAuthorizationToken
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                  - ecr:TagResource
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:CreateLoadBalancer
                  - elasticloadbalancing:CreateTargetGroup
                  - elasticloadbalancing:CreateListener
                  - elasticloadbalancing:CreateRule
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeTargetGroupAttributes
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:DescribeRules
                  - elasticloadbalancing:ModifyLoadBalancerAttributes
                  - elasticloadbalancing:ModifyTargetGroupAttributes
                  - elasticloadbalancing:ModifyListener
                  - elasticloadbalancing:ModifyRule
                  - elasticloadbalancing:SetSecurityGroups
                  - elasticloadbalancing:DeleteLoadBalancer
                  - elasticloadbalancing:DeleteTargetGroup
                  - elasticloadbalancing:DeleteListener
                  - elasticloadbalancing:DeleteRule
                  - elasticloadbalancing:AddTags
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:CreateSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeVpcs
                  - ec2:DescribeSubnets
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeAccountAttributes
                  - ec2:DeleteSecurityGroup
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:CreateTags
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:PutRetentionPolicy
                  - logs:DescribeLogGroups
                  - logs:FilterLogEvents
                  - logs:DeleteLogGroup
                  - logs:TagResource
                  - logs:TagLogGroup
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource: arn:aws:ssm:*:*:parameter/cdk-bootstrap/*
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:GetTemplateSummary
                Resource: '*'
              - Effect: Allow
                Action:
                  - tag:GetResources
                Resource: '*'
              - Effect: Allow
                Action:
                  - acm:RequestCertificate
                  - acm:DescribeCertificate
                  - acm:DeleteCertificate
                  - acm:ListCertificates
                  - acm:AddTagsToCertificate
                Resource: '*'
              - Effect: Allow
                Action:
                  - route53:ChangeResourceRecordSets
                  - route53:GetHostedZone
                  - route53:GetChange
                  - route53:ListHostedZonesByName
                  - route53:CreateHostedZone
                  - route53:ChangeTagsForResource
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:PassRole
                  - iam:GetRole
                  - iam:TagRole
                  - iam:CreateOpenIDConnectProvider
                  - iam:GetOpenIDConnectProvider
                  - iam:DeleteOpenIDConnectProvider
                  - iam:ListOpenIDConnectProviders
                  - iam:TagOpenIDConnectProvider
                  - iam:CreateServiceLinkedRole
                Resource: '*'
              - Effect: Allow
                Action:
                  - secretsmanager:CreateSecret
                  - secretsmanager:DeleteSecret
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetRandomPassword
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                  - secretsmanager:TagResource
                  - secretsmanager:UpdateSecret
                Resource: '*'
              - Effect: Allow
                Action:
                  - rds:CreateDBInstance
                  - rds:DeleteDBInstance
                  - rds:DescribeDBInstances
                  - rds:ModifyDBInstance
                  - rds:CreateDBSubnetGroup
                  - rds:DeleteDBSubnetGroup
                  - rds:DescribeDBSubnetGroups
                  - rds:AddTagsToResource
                  - rds:ListTagsForResource
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:AddTagsToResource
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:PutBucketVersioning
                  - s3:PutBucketPublicAccessBlock
                  - s3:HeadBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:TagResource
                Resource: '*'

Outputs:
  StrictOpsRoleArn:
    Description: ARN of the role to provide to StrictOps onboarding.
    Value: !GetAtt StrictOpsCrossAccountRole.Arn
